// <auto-generated />
namespace Kartverket.Register.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CoverageForDatasetIsOptional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CoverageForDatasetIsOptional));
        
        string IMigrationMetadata.Id
        {
            get { return "201904241010486_CoverageForDatasetIsOptional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
