// <auto-generated />
namespace Kartverket.Register.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class AddResponsibleGeoDataCollection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddResponsibleGeoDataCollection));
        
        string IMigrationMetadata.Id
        {
            get { return "202103080901240_AddResponsibleGeoDataCollection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
