// <auto-generated />
namespace Kartverket.Register.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class AddGradeForMareanoReport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGradeForMareanoReport));
        
        string IMigrationMetadata.Id
        {
            get { return "202112211112105_AddGradeForMareanoReport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
