// <auto-generated />
namespace Kartverket.Register.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddSchematronFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSchematronFile));
        
        string IMigrationMetadata.Id
        {
            get { return "202210101305133_AddSchematronFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
