// <auto-generated />
namespace Kartverket.Register.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddFairI3_c_Criteria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFairI3_c_Criteria));
        
        string IMigrationMetadata.Id
        {
            get { return "202411260702025_AddFairI3_c_Criteria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
