//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:4.0.30319.42000
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Eu.Europa.Ec.Jrc.Inspire {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/basictype")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/basictype", IsNullable=false)]
    public partial class Time {
        
        private string hourField;
        
        private string minuteField;
        
        private string secondField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hour {
            get {
                return this.hourField;
            }
            set {
                this.hourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string minute {
            get {
                return this.minuteField;
            }
            set {
                this.minuteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string second {
            get {
                return this.secondField;
            }
            set {
                this.secondField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/basictype")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/basictype", IsNullable=false)]
    public partial class Date {
        
        private string dayField;
        
        private string monthField;
        
        private string yearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/basictype")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/basictype", IsNullable=false)]
    public partial class DateTime {
        
        private string dayField;
        
        private string monthField;
        
        private string yearField;
        
        private string hourField;
        
        private string minuteField;
        
        private string secondField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hour {
            get {
                return this.hourField;
            }
            set {
                this.hourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string minute {
            get {
                return this.minuteField;
            }
            set {
                this.minuteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string second {
            get {
                return this.secondField;
            }
            set {
                this.secondField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/monitoring")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/monitoring", IsNullable=false)]
    public partial class Monitoring {
        
        private Date documentYearField;
        
        private CountryCode memberStateField;
        
        private MonitoringMD monitoringMDField;
        
        private Indicators indicatorsField;
        
        private RowData rowDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Date documentYear {
            get {
                return this.documentYearField;
            }
            set {
                this.documentYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CountryCode memberState {
            get {
                return this.memberStateField;
            }
            set {
                this.memberStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MonitoringMD MonitoringMD {
            get {
                return this.monitoringMDField;
            }
            set {
                this.monitoringMDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Indicators Indicators {
            get {
                return this.indicatorsField;
            }
            set {
                this.indicatorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RowData RowData {
            get {
                return this.rowDataField;
            }
            set {
                this.rowDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/basictype")]
    public enum CountryCode {
        
        /// <remarks/>
        AT,
        
        /// <remarks/>
        BE,
        
        /// <remarks/>
        BG,
        
        /// <remarks/>
        HR,
        
        /// <remarks/>
        CY,
        
        /// <remarks/>
        CZ,
        
        /// <remarks/>
        DK,
        
        /// <remarks/>
        EE,
        
        /// <remarks/>
        FI,
        
        /// <remarks/>
        FR,
        
        /// <remarks/>
        DE,
        
        /// <remarks/>
        EL,
        
        /// <remarks/>
        HU,
        
        /// <remarks/>
        IS,
        
        /// <remarks/>
        IE,
        
        /// <remarks/>
        IT,
        
        /// <remarks/>
        LV,
        
        /// <remarks/>
        LI,
        
        /// <remarks/>
        LT,
        
        /// <remarks/>
        LU,
        
        /// <remarks/>
        MT,
        
        /// <remarks/>
        NL,
        
        /// <remarks/>
        NO,
        
        /// <remarks/>
        PL,
        
        /// <remarks/>
        PT,
        
        /// <remarks/>
        RO,
        
        /// <remarks/>
        SK,
        
        /// <remarks/>
        SI,
        
        /// <remarks/>
        ES,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        CH,
        
        /// <remarks/>
        UK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/monitoringmd")]
    public partial class MonitoringMD {
        
        private string organizationNameField;
        
        private string emailField;
        
        private Date monitoringDateField;
        
        private LanguageCode languageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string organizationName {
            get {
                return this.organizationNameField;
            }
            set {
                this.organizationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Date monitoringDate {
            get {
                return this.monitoringDateField;
            }
            set {
                this.monitoringDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LanguageCode language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/basictype")]
    public enum LanguageCode {
        
        /// <remarks/>
        bul,
        
        /// <remarks/>
        cze,
        
        /// <remarks/>
        dan,
        
        /// <remarks/>
        dut,
        
        /// <remarks/>
        eng,
        
        /// <remarks/>
        est,
        
        /// <remarks/>
        fin,
        
        /// <remarks/>
        fre,
        
        /// <remarks/>
        ger,
        
        /// <remarks/>
        gre,
        
        /// <remarks/>
        hrv,
        
        /// <remarks/>
        hun,
        
        /// <remarks/>
        ice,
        
        /// <remarks/>
        gle,
        
        /// <remarks/>
        ita,
        
        /// <remarks/>
        lav,
        
        /// <remarks/>
        lit,
        
        /// <remarks/>
        mlt,
        
        /// <remarks/>
        nor,
        
        /// <remarks/>
        pol,
        
        /// <remarks/>
        por,
        
        /// <remarks/>
        rum,
        
        /// <remarks/>
        slo,
        
        /// <remarks/>
        slv,
        
        /// <remarks/>
        spa,
        
        /// <remarks/>
        swe,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/indicators")]
    public partial class Indicators {
        
        private NnConformityIndicators nnConformityIndicatorsField;
        
        private GeoCoverageIndicators geoCoverageIndicatorsField;
        
        private UseNNindicators useNNindicatorsField;
        
        private MetadataExistenceIndicators metadataExistenceIndicatorsField;
        
        private DiscoveryMetadataIndicators discoveryMetadataIndicatorsField;
        
        private ViewDownloadAccessibilityIndicators viewDownloadAccessibilityIndicatorsField;
        
        private SpatialDataAndService spatialDataAndServiceField;
        
        private MetadataConformityIndicators metadataConformityIndicatorsField;
        
        private SdsConformantIndicators sdsConformantIndicatorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public NnConformityIndicators NnConformityIndicators {
            get {
                return this.nnConformityIndicatorsField;
            }
            set {
                this.nnConformityIndicatorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GeoCoverageIndicators GeoCoverageIndicators {
            get {
                return this.geoCoverageIndicatorsField;
            }
            set {
                this.geoCoverageIndicatorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UseNNindicators UseNNindicators {
            get {
                return this.useNNindicatorsField;
            }
            set {
                this.useNNindicatorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MetadataExistenceIndicators MetadataExistenceIndicators {
            get {
                return this.metadataExistenceIndicatorsField;
            }
            set {
                this.metadataExistenceIndicatorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DiscoveryMetadataIndicators DiscoveryMetadataIndicators {
            get {
                return this.discoveryMetadataIndicatorsField;
            }
            set {
                this.discoveryMetadataIndicatorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ViewDownloadAccessibilityIndicators ViewDownloadAccessibilityIndicators {
            get {
                return this.viewDownloadAccessibilityIndicatorsField;
            }
            set {
                this.viewDownloadAccessibilityIndicatorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SpatialDataAndService SpatialDataAndService {
            get {
                return this.spatialDataAndServiceField;
            }
            set {
                this.spatialDataAndServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MetadataConformityIndicators MetadataConformityIndicators {
            get {
                return this.metadataConformityIndicatorsField;
            }
            set {
                this.metadataConformityIndicatorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SdsConformantIndicators SdsConformantIndicators {
            get {
                return this.sdsConformantIndicatorsField;
            }
            set {
                this.sdsConformantIndicatorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/indicators")]
    public partial class NnConformityIndicators {
        
        private double nSi41Field;
        
        private double nSi42Field;
        
        private double nSi43Field;
        
        private double nSi44Field;
        
        private double nSi45Field;
        
        private double nSi4Field;
        
        private NnConformity nnConformityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double NSi41 {
            get {
                return this.nSi41Field;
            }
            set {
                this.nSi41Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double NSi42 {
            get {
                return this.nSi42Field;
            }
            set {
                this.nSi42Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double NSi43 {
            get {
                return this.nSi43Field;
            }
            set {
                this.nSi43Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double NSi44 {
            get {
                return this.nSi44Field;
            }
            set {
                this.nSi44Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double NSi45 {
            get {
                return this.nSi45Field;
            }
            set {
                this.nSi45Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double NSi4 {
            get {
                return this.nSi4Field;
            }
            set {
                this.nSi4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public NnConformity NnConformity {
            get {
                return this.nnConformityField;
            }
            set {
                this.nnConformityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/indicators")]
    public partial class NnConformity {
        
        private int nSv41Field;
        
        private int nSv42Field;
        
        private int nSv43Field;
        
        private int nSv44Field;
        
        private int nSv45Field;
        
        private int nSv4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv41 {
            get {
                return this.nSv41Field;
            }
            set {
                this.nSv41Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv42 {
            get {
                return this.nSv42Field;
            }
            set {
                this.nSv42Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv43 {
            get {
                return this.nSv43Field;
            }
            set {
                this.nSv43Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv44 {
            get {
                return this.nSv44Field;
            }
            set {
                this.nSv44Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv45 {
            get {
                return this.nSv45Field;
            }
            set {
                this.nSv45Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv4 {
            get {
                return this.nSv4Field;
            }
            set {
                this.nSv4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/indicators")]
    public partial class GeoCoverageIndicators {
        
        private double dSi11Field;
        
        private double dSi12Field;
        
        private double dSi13Field;
        
        private double dSi1Field;
        
        private GeoCoverageSDS geoCoverageSDSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double DSi11 {
            get {
                return this.dSi11Field;
            }
            set {
                this.dSi11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double DSi12 {
            get {
                return this.dSi12Field;
            }
            set {
                this.dSi12Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double DSi13 {
            get {
                return this.dSi13Field;
            }
            set {
                this.dSi13Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double DSi1 {
            get {
                return this.dSi1Field;
            }
            set {
                this.dSi1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GeoCoverageSDS GeoCoverageSDS {
            get {
                return this.geoCoverageSDSField;
            }
            set {
                this.geoCoverageSDSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/indicators")]
    public partial class GeoCoverageSDS {
        
        private double dSv11_ActAreaField;
        
        private double dSv12_ActAreaField;
        
        private double dSv13_ActAreaField;
        
        private double dSv1_ActAreaField;
        
        private double dSv11_RelAreaField;
        
        private double dSv12_RelAreaField;
        
        private double dSv13_RelAreaField;
        
        private double dSv1_RelAreaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double DSv11_ActArea {
            get {
                return this.dSv11_ActAreaField;
            }
            set {
                this.dSv11_ActAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double DSv12_ActArea {
            get {
                return this.dSv12_ActAreaField;
            }
            set {
                this.dSv12_ActAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double DSv13_ActArea {
            get {
                return this.dSv13_ActAreaField;
            }
            set {
                this.dSv13_ActAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double DSv1_ActArea {
            get {
                return this.dSv1_ActAreaField;
            }
            set {
                this.dSv1_ActAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double DSv11_RelArea {
            get {
                return this.dSv11_RelAreaField;
            }
            set {
                this.dSv11_RelAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double DSv12_RelArea {
            get {
                return this.dSv12_RelAreaField;
            }
            set {
                this.dSv12_RelAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double DSv13_RelArea {
            get {
                return this.dSv13_RelAreaField;
            }
            set {
                this.dSv13_RelAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double DSv1_RelArea {
            get {
                return this.dSv1_RelAreaField;
            }
            set {
                this.dSv1_RelAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/indicators")]
    public partial class UseNNindicators {
        
        private double nSi31Field;
        
        private double nSi32Field;
        
        private double nSi33Field;
        
        private double nSi34Field;
        
        private double nSi35Field;
        
        private double nSi3Field;
        
        private UseNN useNNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double NSi31 {
            get {
                return this.nSi31Field;
            }
            set {
                this.nSi31Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double NSi32 {
            get {
                return this.nSi32Field;
            }
            set {
                this.nSi32Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double NSi33 {
            get {
                return this.nSi33Field;
            }
            set {
                this.nSi33Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double NSi34 {
            get {
                return this.nSi34Field;
            }
            set {
                this.nSi34Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double NSi35 {
            get {
                return this.nSi35Field;
            }
            set {
                this.nSi35Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double NSi3 {
            get {
                return this.nSi3Field;
            }
            set {
                this.nSi3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UseNN UseNN {
            get {
                return this.useNNField;
            }
            set {
                this.useNNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/indicators")]
    public partial class UseNN {
        
        private int nSv31Field;
        
        private int nSv32Field;
        
        private int nSv33Field;
        
        private int nSv34Field;
        
        private int nSv35Field;
        
        private int nSv3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv31 {
            get {
                return this.nSv31Field;
            }
            set {
                this.nSv31Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv32 {
            get {
                return this.nSv32Field;
            }
            set {
                this.nSv32Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv33 {
            get {
                return this.nSv33Field;
            }
            set {
                this.nSv33Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv34 {
            get {
                return this.nSv34Field;
            }
            set {
                this.nSv34Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv35 {
            get {
                return this.nSv35Field;
            }
            set {
                this.nSv35Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv3 {
            get {
                return this.nSv3Field;
            }
            set {
                this.nSv3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/indicators")]
    public partial class MetadataExistenceIndicators {
        
        private double mDi11Field;
        
        private double mDi12Field;
        
        private double mDi13Field;
        
        private double mDi14Field;
        
        private double mDi1Field;
        
        private MetadataExistence metadataExistenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double MDi11 {
            get {
                return this.mDi11Field;
            }
            set {
                this.mDi11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double MDi12 {
            get {
                return this.mDi12Field;
            }
            set {
                this.mDi12Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double MDi13 {
            get {
                return this.mDi13Field;
            }
            set {
                this.mDi13Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double MDi14 {
            get {
                return this.mDi14Field;
            }
            set {
                this.mDi14Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double MDi1 {
            get {
                return this.mDi1Field;
            }
            set {
                this.mDi1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MetadataExistence MetadataExistence {
            get {
                return this.metadataExistenceField;
            }
            set {
                this.metadataExistenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/indicators")]
    public partial class MetadataExistence {
        
        private int mDv11Field;
        
        private int mDv12Field;
        
        private int mDv13Field;
        
        private int mDv1_DSField;
        
        private int mDv14Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int MDv11 {
            get {
                return this.mDv11Field;
            }
            set {
                this.mDv11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int MDv12 {
            get {
                return this.mDv12Field;
            }
            set {
                this.mDv12Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int MDv13 {
            get {
                return this.mDv13Field;
            }
            set {
                this.mDv13Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int MDv1_DS {
            get {
                return this.mDv1_DSField;
            }
            set {
                this.mDv1_DSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int MDv14 {
            get {
                return this.mDv14Field;
            }
            set {
                this.mDv14Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/indicators")]
    public partial class DiscoveryMetadataIndicators {
        
        private double nSi11Field;
        
        private double nSi12Field;
        
        private double nSi1Field;
        
        private DiscoveryMetadata discoveryMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double NSi11 {
            get {
                return this.nSi11Field;
            }
            set {
                this.nSi11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double NSi12 {
            get {
                return this.nSi12Field;
            }
            set {
                this.nSi12Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double NSi1 {
            get {
                return this.nSi1Field;
            }
            set {
                this.nSi1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DiscoveryMetadata DiscoveryMetadata {
            get {
                return this.discoveryMetadataField;
            }
            set {
                this.discoveryMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/indicators")]
    public partial class DiscoveryMetadata {
        
        private int nSv11Field;
        
        private int nSv12Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv11 {
            get {
                return this.nSv11Field;
            }
            set {
                this.nSv11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv12 {
            get {
                return this.nSv12Field;
            }
            set {
                this.nSv12Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/indicators")]
    public partial class ViewDownloadAccessibilityIndicators {
        
        private double nSi21Field;
        
        private double nSi22Field;
        
        private double nSi2Field;
        
        private ViewDownloadAccessibility viewDownloadAccessibilityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double NSi21 {
            get {
                return this.nSi21Field;
            }
            set {
                this.nSi21Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double NSi22 {
            get {
                return this.nSi22Field;
            }
            set {
                this.nSi22Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double NSi2 {
            get {
                return this.nSi2Field;
            }
            set {
                this.nSi2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ViewDownloadAccessibility ViewDownloadAccessibility {
            get {
                return this.viewDownloadAccessibilityField;
            }
            set {
                this.viewDownloadAccessibilityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/indicators")]
    public partial class ViewDownloadAccessibility {
        
        private int nSv21Field;
        
        private int nSv22Field;
        
        private int nSv23Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv21 {
            get {
                return this.nSv21Field;
            }
            set {
                this.nSv21Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv22 {
            get {
                return this.nSv22Field;
            }
            set {
                this.nSv22Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv23 {
            get {
                return this.nSv23Field;
            }
            set {
                this.nSv23Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/indicators")]
    public partial class SpatialDataAndService {
        
        private int dSv_Num1Field;
        
        private int dSv_Num2Field;
        
        private int dSv_Num3Field;
        
        private int dSv_NumField;
        
        private int sDSv_NumField;
        
        private int nSv_NumDiscServField;
        
        private int nSv_NumViewServField;
        
        private int nSv_NumDownServField;
        
        private int nSv_NumInvkServField;
        
        private int nSv_NumAllServField;
        
        private int nSv_NumTransfServField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int DSv_Num1 {
            get {
                return this.dSv_Num1Field;
            }
            set {
                this.dSv_Num1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int DSv_Num2 {
            get {
                return this.dSv_Num2Field;
            }
            set {
                this.dSv_Num2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int DSv_Num3 {
            get {
                return this.dSv_Num3Field;
            }
            set {
                this.dSv_Num3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int DSv_Num {
            get {
                return this.dSv_NumField;
            }
            set {
                this.dSv_NumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int SDSv_Num {
            get {
                return this.sDSv_NumField;
            }
            set {
                this.sDSv_NumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv_NumDiscServ {
            get {
                return this.nSv_NumDiscServField;
            }
            set {
                this.nSv_NumDiscServField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv_NumViewServ {
            get {
                return this.nSv_NumViewServField;
            }
            set {
                this.nSv_NumViewServField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv_NumDownServ {
            get {
                return this.nSv_NumDownServField;
            }
            set {
                this.nSv_NumDownServField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv_NumInvkServ {
            get {
                return this.nSv_NumInvkServField;
            }
            set {
                this.nSv_NumInvkServField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv_NumAllServ {
            get {
                return this.nSv_NumAllServField;
            }
            set {
                this.nSv_NumAllServField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NSv_NumTransfServ {
            get {
                return this.nSv_NumTransfServField;
            }
            set {
                this.nSv_NumTransfServField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/indicators")]
    public partial class MetadataConformityIndicators {
        
        private double mDi21Field;
        
        private double mDi22Field;
        
        private double mDi23Field;
        
        private double mDi24Field;
        
        private double mDi2Field;
        
        private MetadataConformity metadataConformityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double MDi21 {
            get {
                return this.mDi21Field;
            }
            set {
                this.mDi21Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double MDi22 {
            get {
                return this.mDi22Field;
            }
            set {
                this.mDi22Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double MDi23 {
            get {
                return this.mDi23Field;
            }
            set {
                this.mDi23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double MDi24 {
            get {
                return this.mDi24Field;
            }
            set {
                this.mDi24Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double MDi2 {
            get {
                return this.mDi2Field;
            }
            set {
                this.mDi2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MetadataConformity MetadataConformity {
            get {
                return this.metadataConformityField;
            }
            set {
                this.metadataConformityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/indicators")]
    public partial class MetadataConformity {
        
        private int mDv21Field;
        
        private int mDv22Field;
        
        private int mDv23Field;
        
        private int mDv2_DSField;
        
        private int mDv24Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int MDv21 {
            get {
                return this.mDv21Field;
            }
            set {
                this.mDv21Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int MDv22 {
            get {
                return this.mDv22Field;
            }
            set {
                this.mDv22Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int MDv23 {
            get {
                return this.mDv23Field;
            }
            set {
                this.mDv23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int MDv2_DS {
            get {
                return this.mDv2_DSField;
            }
            set {
                this.mDv2_DSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int MDv24 {
            get {
                return this.mDv24Field;
            }
            set {
                this.mDv24Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/indicators")]
    public partial class SdsConformantIndicators {
        
        private double dSi21Field;
        
        private double dSi22Field;
        
        private double dSi23Field;
        
        private double dSi2Field;
        
        private SdsConformant sdsConformantField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double DSi21 {
            get {
                return this.dSi21Field;
            }
            set {
                this.dSi21Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double DSi22 {
            get {
                return this.dSi22Field;
            }
            set {
                this.dSi22Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double DSi23 {
            get {
                return this.dSi23Field;
            }
            set {
                this.dSi23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double DSi2 {
            get {
                return this.dSi2Field;
            }
            set {
                this.dSi2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SdsConformant SdsConformant {
            get {
                return this.sdsConformantField;
            }
            set {
                this.sdsConformantField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/indicators")]
    public partial class SdsConformant {
        
        private int dSv21Field;
        
        private int dSv22Field;
        
        private int dSv23Field;
        
        private int dSv2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int DSv21 {
            get {
                return this.dSv21Field;
            }
            set {
                this.dSv21Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int DSv22 {
            get {
                return this.dSv22Field;
            }
            set {
                this.dSv22Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int DSv23 {
            get {
                return this.dSv23Field;
            }
            set {
                this.dSv23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int DSv2 {
            get {
                return this.dSv2Field;
            }
            set {
                this.dSv2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/rowdata")]
    public partial class RowData {
        
        private SpatialDataService[] spatialDataServiceField;
        
        private SpatialDataSet[] spatialDataSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SpatialDataService", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SpatialDataService[] SpatialDataService {
            get {
                return this.spatialDataServiceField;
            }
            set {
                this.spatialDataServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SpatialDataSet", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SpatialDataSet[] SpatialDataSet {
            get {
                return this.spatialDataSetField;
            }
            set {
                this.spatialDataSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/rowdata")]
    public partial class SpatialDataService : SpatialResource {
        
        private MdServiceExistence mdServiceExistenceField;
        
        private NetworkService networkServiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MdServiceExistence MdServiceExistence {
            get {
                return this.mdServiceExistenceField;
            }
            set {
                this.mdServiceExistenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public NetworkService NetworkService {
            get {
                return this.networkServiceField;
            }
            set {
                this.networkServiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/rowdata")]
    public partial class MdServiceExistence {
        
        private bool mdConformityField;
        
        private bool discoveryAccessibilityField;
        
        private string discoveryAccessibilityUuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool mdConformity {
            get {
                return this.mdConformityField;
            }
            set {
                this.mdConformityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool discoveryAccessibility {
            get {
                return this.discoveryAccessibilityField;
            }
            set {
                this.discoveryAccessibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string discoveryAccessibilityUuid {
            get {
                return this.discoveryAccessibilityUuidField;
            }
            set {
                this.discoveryAccessibilityUuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/rowdata")]
    public partial class NetworkService {
        
        private bool directlyAccessibleField;
        
        private string uRLField;
        
        private int userRequestField;
        
        private bool nnConformityField;
        
        private NnServiceType nnServiceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool directlyAccessible {
            get {
                return this.directlyAccessibleField;
            }
            set {
                this.directlyAccessibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int userRequest {
            get {
                return this.userRequestField;
            }
            set {
                this.userRequestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool nnConformity {
            get {
                return this.nnConformityField;
            }
            set {
                this.nnConformityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public NnServiceType NnServiceType {
            get {
                return this.nnServiceTypeField;
            }
            set {
                this.nnServiceTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/rowdata")]
    public enum NnServiceType {
        
        /// <remarks/>
        discovery,
        
        /// <remarks/>
        view,
        
        /// <remarks/>
        download,
        
        /// <remarks/>
        transformation,
        
        /// <remarks/>
        invoke,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SpatialDataService))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SpatialDataSet))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/rowdata")]
    public partial class SpatialResource {
        
        private string nameField;
        
        private string respAuthorityField;
        
        private string uuidField;
        
        private Themes[] themesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string respAuthority {
            get {
                return this.respAuthorityField;
            }
            set {
                this.respAuthorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Themes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Themes[] Themes {
            get {
                return this.themesField;
            }
            set {
                this.themesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/rowdata")]
    public partial class Themes {
        
        private AnnexIII[] annexIIIField;
        
        private AnnexI[] annexIField;
        
        private AnnexII[] annexIIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnnexIII", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AnnexIII[] AnnexIII {
            get {
                return this.annexIIIField;
            }
            set {
                this.annexIIIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnnexI", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AnnexI[] AnnexI {
            get {
                return this.annexIField;
            }
            set {
                this.annexIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnnexII", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AnnexII[] AnnexII {
            get {
                return this.annexIIField;
            }
            set {
                this.annexIIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/rowdata")]
    public enum AnnexIII {
        
        /// <remarks/>
        statisticalUnits,
        
        /// <remarks/>
        buildings,
        
        /// <remarks/>
        soil,
        
        /// <remarks/>
        landUse,
        
        /// <remarks/>
        humanHealthAndSafety,
        
        /// <remarks/>
        utilityAndGovernmentalServices,
        
        /// <remarks/>
        environmentalMonitoringFacilities,
        
        /// <remarks/>
        productionAndIndustrialFacilities,
        
        /// <remarks/>
        agriculturalAndAquacultureFacilities,
        
        /// <remarks/>
        populationDistributionDemography,
        
        /// <remarks/>
        areaManagementRestrictionRegulationZonesAndReportingUnits,
        
        /// <remarks/>
        naturalRiskZones,
        
        /// <remarks/>
        atmosphericConditions,
        
        /// <remarks/>
        meteorologicalGeographicalFeatures,
        
        /// <remarks/>
        oceanographicGeographicalFeatures,
        
        /// <remarks/>
        seaRegions,
        
        /// <remarks/>
        bioGeographicalRegions,
        
        /// <remarks/>
        habitatsAndBiotopes,
        
        /// <remarks/>
        speciesDistribution,
        
        /// <remarks/>
        energyResources,
        
        /// <remarks/>
        mineralResources,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/rowdata")]
    public enum AnnexI {
        
        /// <remarks/>
        coordinateReferenceSystems,
        
        /// <remarks/>
        geographicalGridSystems,
        
        /// <remarks/>
        geographicalNames,
        
        /// <remarks/>
        administrativeUnits,
        
        /// <remarks/>
        addresses,
        
        /// <remarks/>
        cadastralParcels,
        
        /// <remarks/>
        transportNetworks,
        
        /// <remarks/>
        hydrography,
        
        /// <remarks/>
        protectedSites,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/rowdata")]
    public enum AnnexII {
        
        /// <remarks/>
        elevation,
        
        /// <remarks/>
        landCover,
        
        /// <remarks/>
        orthoimagery,
        
        /// <remarks/>
        geology,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/rowdata")]
    public partial class SpatialDataSet : SpatialResource {
        
        private Coverage coverageField;
        
        private MdDataSetExistence mdDataSetExistenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Coverage Coverage {
            get {
                return this.coverageField;
            }
            set {
                this.coverageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MdDataSetExistence MdDataSetExistence {
            get {
                return this.mdDataSetExistenceField;
            }
            set {
                this.mdDataSetExistenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/rowdata")]
    public partial class Coverage {
        
        private double relevantAreaField;
        
        private double actualAreaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double relevantArea {
            get {
                return this.relevantAreaField;
            }
            set {
                this.relevantAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double actualArea {
            get {
                return this.actualAreaField;
            }
            set {
                this.actualAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/rowdata")]
    public partial class MdDataSetExistence {
        
        private IRConformity iRConformityField;
        
        private MdAccessibility mdAccessibilityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IRConformity IRConformity {
            get {
                return this.iRConformityField;
            }
            set {
                this.iRConformityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MdAccessibility MdAccessibility {
            get {
                return this.mdAccessibilityField;
            }
            set {
                this.mdAccessibilityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/rowdata")]
    public partial class IRConformity {
        
        private bool structureComplianceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool structureCompliance {
            get {
                return this.structureComplianceField;
            }
            set {
                this.structureComplianceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inspire.jrc.ec.europa.eu/monitoringreporting/rowdata")]
    public partial class MdAccessibility {
        
        private bool discoveryField;
        
        private string discoveryUuidField;
        
        private bool viewField;
        
        private string viewUuidField;
        
        private bool downloadField;
        
        private string downloadUuidField;
        
        private bool viewDownloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool discovery {
            get {
                return this.discoveryField;
            }
            set {
                this.discoveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string discoveryUuid {
            get {
                return this.discoveryUuidField;
            }
            set {
                this.discoveryUuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool view {
            get {
                return this.viewField;
            }
            set {
                this.viewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string viewUuid {
            get {
                return this.viewUuidField;
            }
            set {
                this.viewUuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool download {
            get {
                return this.downloadField;
            }
            set {
                this.downloadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string downloadUuid {
            get {
                return this.downloadUuidField;
            }
            set {
                this.downloadUuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool viewDownload {
            get {
                return this.viewDownloadField;
            }
            set {
                this.viewDownloadField = value;
            }
        }
    }
}
