///////////////////////////////////////////////////////////
//  DOKTheme.cs
//  Implementation of the Class DOKTheme
//  Generated by Enterprise Architect
//  Created on:      24-nov-2014 22:43:39
//  Original author: Tor Kjetil
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;
using Kartverket.Register.Helpers;
using Kartverket.Register.Models.Translations;

namespace Kartverket.Register.Models {
	public class DOKTheme {
        [Key]
        public string value { get; set; }
        public string description { get; set; }


	    public string DescriptionTranslated()
	    {
	        var cultureName = CultureHelper.GetCurrentCulture();
	        var DOKThemeDescription = description;
	        if (!CultureHelper.IsNorwegian())
	            DOKThemeDescription = GetTranslation(value);

	        return DOKThemeDescription;
	    }

        private string GetTranslation(string value)
        {
            var translated = DOKThemeTranslation.NorwegianToEnglish[value];
            if (translated != null)
                return translated;

            return value;
        }
    }//end DOKTheme

}//end namespace Datamodell