///////////////////////////////////////////////////////////
//  EPSG.cs
//  Implementation of the Class EPSG
//  Generated by Enterprise Architect
//  Created on:      24-nov-2014 22:43:42
//  Original author: Tor Kjetil
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Kartverket.Register.Models
{
	public class EPSG : RegisterItem {

        public string epsg { get; set; }
        public string sosiReferencesystem { get; set; }
        public string externalReference { get; set; }

		

	}//end EPSG

}//end namespace Datamodell