///////////////////////////////////////////////////////////
//  Register.cs
//  Implementation of the Class Register
//  Generated by Enterprise Architect
//  Created on:      24-nov-2014 22:43:51
//  Original author: Tor Kjetil
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;



namespace Kartverket.Register.Models
{
    public class Register
    {
        public Register() 
        {
            this.items = new HashSet<RegisterItem>();
            this.subregisters = new HashSet<Register>();
            this.replaces = new HashSet<Version>();
        }
        [Key]
        public Guid systemId { get; set; }
        public virtual Version currentVersion { get; set; }
        public virtual ICollection<Version> replaces { get; set; }
        public virtual Organization owner { get; set; }
        public virtual Organization manager { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public virtual Status status { get; set; }
        public DateTime dateSubmitted { get; set; }
        public DateTime modified { get; set; }
        public DateTime? dateAccepted { get; set; }
        public string containedItemClass { get; set; }
        public virtual ICollection<RegisterItem> items { get; set; }
        //public virtual Register parentRegister { get; set; }
        public virtual ICollection<Register> subregisters { get; set; }

		

	}//end Register

}//end namespace Datamodell