///////////////////////////////////////////////////////////
//  Version.cs
//  Implementation of the Class Version
//  Generated by Enterprise Architect
//  Created on:      24-nov-2014 22:43:57
//  Original author: Tor Kjetil
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;



namespace Kartverket.Register.Models
{
	public class Version {
        [Key]    
        public Guid systemId { get; set; }
        public string containedItemClass { get; set; }
        public Guid currentVersion { get; set; }
        public int lastVersionNumber { get; set; }
        
	}//end Version

}//end namespace Datamodell