//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CodelistValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodelistValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kartverket.Register.Resources.CodelistValues", typeof(CodelistValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mer generelt begrep.
        /// </summary>
        public static string BroaderItem {
            get {
                return ResourceManager.GetString("BroaderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodeliste.
        /// </summary>
        public static string Codelist {
            get {
                return ResourceManager.GetString("Codelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodeverdi.
        /// </summary>
        public static string CodeValue {
            get {
                return ResourceManager.GetString("CodeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodeverdi engelsk.
        /// </summary>
        public static string CodeValueEnglish {
            get {
                return ResourceManager.GetString("CodeValueEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodeverdier.
        /// </summary>
        public static string CodeValues {
            get {
                return ResourceManager.GetString("CodeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreslå ny kodeverdi.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filen har feil innhold!.
        /// </summary>
        public static string ErrorMessagefile {
            get {
                return ResourceManager.GetString("ErrorMessagefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekstern id.
        /// </summary>
        public static string ExternalId {
            get {
                return ResourceManager.GetString("ExternalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarkiske kodelister.
        /// </summary>
        public static string HierarchicalCodelists {
            get {
                return ResourceManager.GetString("HierarchicalCodelists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg hvilke kodeverdier som skal ligge over og under kodeverdien i hierarkiet.
        /// </summary>
        public static string HierarchicalCodelistsSelectionText {
            get {
                return ResourceManager.GetString("HierarchicalCodelistsSelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import fra CSV fil.
        /// </summary>
        public static string ImportFile {
            get {
                return ResourceManager.GetString("ImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg csv fil i UTF-8 med kodeliste.
        /// </summary>
        public static string ImportFileInfo {
            get {
                return ResourceManager.GetString("ImportFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mer spesialiserte begrep.
        /// </summary>
        public static string NarrowerItems {
            get {
                return ResourceManager.GetString("NarrowerItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to velg kodeverdi.
        /// </summary>
        public static string SelectCodeValue {
            get {
                return ResourceManager.GetString("SelectCodeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyldig fra.
        /// </summary>
        public static string ValidFromDate {
            get {
                return ResourceManager.GetString("ValidFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyldig til.
        /// </summary>
        public static string ValidToDate {
            get {
                return ResourceManager.GetString("ValidToDate", resourceCulture);
            }
        }
    }
}
