//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DokCoverage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DokCoverage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kartverket.Register.Resources.DokCoverage", typeof(DokCoverage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dekningsområde for dette datasettet.
        /// </summary>
        public static string AreaForDataset {
            get {
                return ResourceManager.GetString("AreaForDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommunen har bekreftet dette datasettet.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg datasett.
        /// </summary>
        public static string DatasetSelection {
            get {
                return ResourceManager.GetString("DatasetSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg DOK-datasett.
        /// </summary>
        public static string DokDatasetSelection {
            get {
                return ResourceManager.GetString("DokDatasetSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis markører.
        /// </summary>
        public static string ShowMarker {
            get {
                return ResourceManager.GetString("ShowMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dekningskart for DOK-datasett.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg zoom-nivå.
        /// </summary>
        public static string ZoomLevelSelection {
            get {
                return ResourceManager.GetString("ZoomLevelSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hele landet.
        /// </summary>
        public static string ZoomLevelSelectionEntireCountry {
            get {
                return ResourceManager.GetString("ZoomLevelSelectionEntireCountry", resourceCulture);
            }
        }
    }
}
