//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kartverket.Register.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeodataCollection {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeodataCollection() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kartverket.Register.Resources.GeodataCollection", typeof(GeodataCollection).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataeier.
        /// </summary>
        public static string DataOwner {
            get {
                return ResourceManager.GetString("DataOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenke til datasett (metadata).
        /// </summary>
        public static string DatasetLink {
            get {
                return ResourceManager.GetString("DatasetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvilket datasett gjelder det.
        /// </summary>
        public static string DatasetTitle {
            get {
                return ResourceManager.GetString("DatasetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributør.
        /// </summary>
        public static string Distributor {
            get {
                return ResourceManager.GetString("Distributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenke til metodikk for kartlegging.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartlegger.
        /// </summary>
        public static string Mapper {
            get {
                return ResourceManager.GetString("Mapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krav til kartlegging.
        /// </summary>
        public static string MappingRequirements {
            get {
                return ResourceManager.GetString("MappingRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mottaksordning - beskrivelse.
        /// </summary>
        public static string Methodology {
            get {
                return ResourceManager.GetString("Methodology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenke til metodikk-dokument.
        /// </summary>
        public static string MethodologyDocumentLink {
            get {
                return ResourceManager.GetString("MethodologyDocumentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenke til metodikk på web.
        /// </summary>
        public static string MethodologyLinkWebPage {
            get {
                return ResourceManager.GetString("MethodologyLinkWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansvarlig etat.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenke til metodikk for avlevering.
        /// </summary>
        public static string ProcessHistory {
            get {
                return ResourceManager.GetString("ProcessHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formål.
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inneholder informasjon og lenke til mottaksordninger for innsamling av Geodata.
        /// </summary>
        public static string RegisterDescription {
            get {
                return ResourceManager.GetString("RegisterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mottaksordninger for innsamling av Geodata.
        /// </summary>
        public static string RegisterName {
            get {
                return ResourceManager.GetString("RegisterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mottaksordning-innsamling-geodata.
        /// </summary>
        public static string RegisterSeoName {
            get {
                return ResourceManager.GetString("RegisterSeoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krav til avlevering.
        /// </summary>
        public static string RegistrationRequirements {
            get {
                return ResourceManager.GetString("RegistrationRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Støtteordninger.
        /// </summary>
        public static string SupportSchemes {
            get {
                return ResourceManager.GetString("SupportSchemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tittel på mottaksordning.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
