//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InspireDataSet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InspireDataSet() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kartverket.Register.Resources.InspireDataSet", typeof(InspireDataSet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arela.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedlastingstjeneste Atom-feed.
        /// </summary>
        public static string AtomFeedStatus {
            get {
                return ResourceManager.GetString("AtomFeedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atom feed.
        /// </summary>
        public static string AtomStatus {
            get {
                return ResourceManager.GetString("AtomStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datadeling.
        /// </summary>
        public static string Distribution {
            get {
                return ResourceManager.GetString("Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deling av data.
        /// </summary>
        public static string DistributionStatus {
            get {
                return ResourceManager.GetString("DistributionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmoniserte data.
        /// </summary>
        public static string HarmonizedDataStatus {
            get {
                return ResourceManager.GetString("HarmonizedDataStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspire tema.
        /// </summary>
        public static string InspireTheme {
            get {
                return ResourceManager.GetString("InspireTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string Metadata {
            get {
                return ResourceManager.GetString("Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata i søketjeneste.
        /// </summary>
        public static string MetadataInSearchService {
            get {
                return ResourceManager.GetString("MetadataInSearchService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadatatjeneste.
        /// </summary>
        public static string MetadataServiceStatus {
            get {
                return ResourceManager.GetString("MetadataServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nettverkstjeneste.
        /// </summary>
        public static string NetworkService {
            get {
                return ResourceManager.GetString("NetworkService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legg til nytt inspire datasett.
        /// </summary>
        public static string NewDataset {
            get {
                return ResourceManager.GetString("NewDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevant area.
        /// </summary>
        public static string RelevantArea {
            get {
                return ResourceManager.GetString("RelevantArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sds.
        /// </summary>
        public static string Sds {
            get {
                return ResourceManager.GetString("Sds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjeneste.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjenestestatus.
        /// </summary>
        public static string ServiceStatus {
            get {
                return ResourceManager.GetString("ServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial data service.
        /// </summary>
        public static string SpatialDataServiceStatus {
            get {
                return ResourceManager.GetString("SpatialDataServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedlastingstjeneste WFS eller Atom-feed.
        /// </summary>
        public static string WfsOrAtomStatus {
            get {
                return ResourceManager.GetString("WfsOrAtomStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedlastingstjeneste WFS.
        /// </summary>
        public static string WfsStatus {
            get {
                return ResourceManager.GetString("WfsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMS.
        /// </summary>
        public static string WmsStatus {
            get {
                return ResourceManager.GetString("WmsStatus", resourceCulture);
            }
        }
    }
}
