//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Organizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Organizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kartverket.Register.Resources.Organizations", typeof(Organizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrasjon.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avtaledokument.
        /// </summary>
        public static string AgreementDocumentUrl {
            get {
                return ResourceManager.GetString("AgreementDocumentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avtale godkjent år.
        /// </summary>
        public static string AgreementYear {
            get {
                return ResourceManager.GetString("AgreementYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv inn et årstall yyyy.
        /// </summary>
        public static string AgreementYearErrorMessage {
            get {
                return ResourceManager.GetString("AgreementYearErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning - øst.
        /// </summary>
        public static string BoundingBoxEast {
            get {
                return ResourceManager.GetString("BoundingBoxEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning - øst er påkrevd.
        /// </summary>
        public static string BoundingBoxEastErrorMessage {
            get {
                return ResourceManager.GetString("BoundingBoxEastErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning - nord.
        /// </summary>
        public static string BoundingBoxNorth {
            get {
                return ResourceManager.GetString("BoundingBoxNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning - nord er påkrevd.
        /// </summary>
        public static string BoundingBoxNorthErrorMessage {
            get {
                return ResourceManager.GetString("BoundingBoxNorthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning - sør.
        /// </summary>
        public static string BoundingBoxSouth {
            get {
                return ResourceManager.GetString("BoundingBoxSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning - sør er påkrevd.
        /// </summary>
        public static string BoundingBoxSouthErrorMessage {
            get {
                return ResourceManager.GetString("BoundingBoxSouthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning - vest.
        /// </summary>
        public static string BoundingBoxWest {
            get {
                return ResourceManager.GetString("BoundingBoxWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning - vest er påkrevd.
        /// </summary>
        public static string BoundingBoxWestErrorMessage {
            get {
                return ResourceManager.GetString("BoundingBoxWestErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktperson.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktperson.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreslå ny organisasjon.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato bekreftet for registrering av kommunalt DOK.
        /// </summary>
        public static string DateConfirmedMunicipalDOK {
            get {
                return ResourceManager.GetString("DateConfirmedMunicipalDOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumenter.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Øst.
        /// </summary>
        public static string East {
            get {
                return ResourceManager.GetString("East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-postadresse.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk senterpunkt.
        /// </summary>
        public static string GeographicCenterPoint {
            get {
                return ResourceManager.GetString("GeographicCenterPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk senterpunkt - x.
        /// </summary>
        public static string GeographicCenterX {
            get {
                return ResourceManager.GetString("GeographicCenterX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk senterpunkt - x er påkrevd.
        /// </summary>
        public static string GeographicCenterXErrorMessage {
            get {
                return ResourceManager.GetString("GeographicCenterXErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk senterpunkt - y.
        /// </summary>
        public static string GeographicCenterY {
            get {
                return ResourceManager.GetString("GeographicCenterY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk senterpunkt - y er påkrevd.
        /// </summary>
        public static string GeographicCenterYErrorMessage {
            get {
                return ResourceManager.GetString("GeographicCenterYErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning.
        /// </summary>
        public static string GeographicExtent {
            get {
                return ResourceManager.GetString("GeographicExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import fra CSV fil.
        /// </summary>
        public static string ImportFromCSV {
            get {
                return ResourceManager.GetString("ImportFromCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg csv fil i UTF-8 med orgnr, navn, beskrivelse, logofilnavn. Logo må lastes opp manuelt til server.
        /// </summary>
        public static string ImportFromCSVInfo {
            get {
                return ResourceManager.GetString("ImportFromCSVInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stor logo.
        /// </summary>
        public static string LargeLogo {
            get {
                return ResourceManager.GetString("LargeLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norge digitaltmedlem.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommunenummer.
        /// </summary>
        public static string MunicipalityCode {
            get {
                return ResourceManager.GetString("MunicipalityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommunenummer er påkrevd.
        /// </summary>
        public static string MunicipalityCodeRequired {
            get {
                return ResourceManager.GetString("MunicipalityCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommunenummeret skal være fire tall inkludert en eventuell 0 som første tall. For eksempel Bø i Telemark har kommunenummer 0821..
        /// </summary>
        public static string MunicipalityHelp {
            get {
                return ResourceManager.GetString("MunicipalityHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommuneinformasjon.
        /// </summary>
        public static string MunicipalityInformation {
            get {
                return ResourceManager.GetString("MunicipalityInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nord.
        /// </summary>
        public static string North {
            get {
                return ResourceManager.GetString("North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjon.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liten logo.
        /// </summary>
        public static string Organization_Logo {
            get {
                return ResourceManager.GetString("Organization_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjonsnavn.
        /// </summary>
        public static string Organization_Name {
            get {
                return ResourceManager.GetString("Organization_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjonsnummer.
        /// </summary>
        public static string Organization_Number {
            get {
                return ResourceManager.GetString("Organization_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjoner.
        /// </summary>
        public static string Organization_s {
            get {
                return ResourceManager.GetString("Organization_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjonstype.
        /// </summary>
        public static string OrganizationType {
            get {
                return ResourceManager.GetString("OrganizationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommune.
        /// </summary>
        public static string OrganizationTypeMunicipality {
            get {
                return ResourceManager.GetString("OrganizationTypeMunicipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinær.
        /// </summary>
        public static string OrganizationTypeRegular {
            get {
                return ResourceManager.GetString("OrganizationTypeRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisskjema/Kalkulator.
        /// </summary>
        public static string PriceFormDocument {
            get {
                return ResourceManager.GetString("PriceFormDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kortnavn.
        /// </summary>
        public static string Shortname {
            get {
                return ResourceManager.GetString("Shortname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sør.
        /// </summary>
        public static string South {
            get {
                return ResourceManager.GetString("South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vest.
        /// </summary>
        public static string West {
            get {
                return ResourceManager.GetString("West", resourceCulture);
            }
        }
    }
}
