//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Registers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Registers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kartverket.Register.Resources.Registers", typeof(Registers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godkjent.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilgang til registeret.
        /// </summary>
        public static string AccessLabel {
            get {
                return ResourceManager.GetString("AccessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjelder tilgang til å foreslå, endre- og slette egne registeroppføringer. Admin har alltid full tilgang.
        /// </summary>
        public static string AccessText {
            get {
                return ResourceManager.GetString("AccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godkjenningstekst.
        /// </summary>
        public static string ApprovalDocument {
            get {
                return ResourceManager.GetString("ApprovalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godkjenningsreferanse.
        /// </summary>
        public static string ApprovalReference {
            get {
                return ResourceManager.GetString("ApprovalReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lovlig innhold.
        /// </summary>
        public static string ContainedItemClass {
            get {
                return ResourceManager.GetString("ContainedItemClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det må settes lovlig innhold for registeret.
        /// </summary>
        public static string ContainedItemClassErrorMessage {
            get {
                return ResourceManager.GetString("ContainedItemClassErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innhold.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjeldende.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato godkjent.
        /// </summary>
        public static string DateAccepted {
            get {
                return ResourceManager.GetString("DateAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato utkast.
        /// </summary>
        public static string DateNotAccepted {
            get {
                return ResourceManager.GetString("DateNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato utgått.
        /// </summary>
        public static string DateRetired {
            get {
                return ResourceManager.GetString("DateRetired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato erstattet.
        /// </summary>
        public static string DateSuperseded {
            get {
                return ResourceManager.GetString("DateSuperseded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er du sikker på at du vil slette.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivelse.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokument url.
        /// </summary>
        public static string DocumentUrl {
            get {
                return ResourceManager.GetString("DocumentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dekningskartet viser hvilke datasett i det offentlige kartgrunnlaget som har dekning i de ulike kommunene..
        /// </summary>
        public static string DOKCoverageContent {
            get {
                return ResourceManager.GetString("DOKCoverageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utkast.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rediger liste.
        /// </summary>
        public static string EditList {
            get {
                return ResourceManager.GetString("EditList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeret kan ikke slettes fordi det inneholder elementer som må slettes først!.
        /// </summary>
        public static string ErrorMessageDelete {
            get {
                return ResourceManager.GetString("ErrorMessageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navnet finnes fra før!.
        /// </summary>
        public static string ErrorMessageValidationName {
            get {
                return ResourceManager.GetString("ErrorMessageValidationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historiske.
        /// </summary>
        public static string Historical {
            get {
                return ResourceManager.GetString("Historical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to treff.
        /// </summary>
        public static string Hits {
            get {
                return ResourceManager.GetString("Hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viser.
        /// </summary>
        public static string HitsDisplay {
            get {
                return ResourceManager.GetString("HitsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to av.
        /// </summary>
        public static string HitsOf {
            get {
                return ResourceManager.GetString("HitsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartografi.
        /// </summary>
        public static string Kartografi {
            get {
                return ResourceManager.GetString("Kartografi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeret inneholder datasett som har registrert digital kartografi.
        /// </summary>
        public static string KartografiContent {
            get {
                return ResourceManager.GetString("KartografiContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Henter register.
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny versjon.
        /// </summary>
        public static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke angitt.
        /// </summary>
        public static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objektregisteret.
        /// </summary>
        public static string Objektregisteret {
            get {
                return ResourceManager.GetString("Objektregisteret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inneholder en samling av sentrale objektkataloger fra SOSI, Inspire og fra parter i Norge digitalt. Her finnes dataspesifikasjoner som er nyttige ved fremstilling av datasett, eller som dokumentasjon av hvordan innholdet og strukturen i et datasett skal tolkes..
        /// </summary>
        public static string ObjektregisteretContent {
            get {
                return ResourceManager.GetString("ObjektregisteretContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eier.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forslag.
        /// </summary>
        public static string Proposal {
            get {
                return ResourceManager.GetString("Proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreslå.
        /// </summary>
        public static string Propose {
            get {
                return ResourceManager.GetString("Propose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publiser.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utgått.
        /// </summary>
        public static string Retired {
            get {
                return ResourceManager.GetString("Retired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innsender.
        /// </summary>
        public static string Submitter {
            get {
                return ResourceManager.GetString("Submitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreslå nytt register.
        /// </summary>
        public static string SuggestNewRegister {
            get {
                return ResourceManager.GetString("SuggestNewRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreslå nytt register i.
        /// </summary>
        public static string SuggestNewRegisterIn {
            get {
                return ResourceManager.GetString("SuggestNewRegisterIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreslå ny versjon av.
        /// </summary>
        public static string SuggestNewVersionOf {
            get {
                return ResourceManager.GetString("SuggestNewVersionOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstattet.
        /// </summary>
        public static string Superseded {
            get {
                return ResourceManager.GetString("Superseded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dette registeret inneholder symboler som brukes til styling av digital kartografi, og til bruk i grafisk bransje..
        /// </summary>
        public static string SymbolContent {
            get {
                return ResourceManager.GetString("SymbolContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppdatert.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utgave.
        /// </summary>
        public static string VersionName {
            get {
                return ResourceManager.GetString("VersionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versjons ID.
        /// </summary>
        public static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
    }
}
