//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Registers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Registers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kartverket.Register.Resources.Registers", typeof(Registers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godkjent.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kun administrator skal ha tilgang til dette registeret.
        /// </summary>
        public static string AccessAdmin {
            get {
                return ResourceManager.GetString("AccessAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor får lov til å forslå, endre og slette egne registeroppføringer (status kan kun endres av administrator).
        /// </summary>
        public static string AccessEditor {
            get {
                return ResourceManager.GetString("AccessEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilgang til registeret.
        /// </summary>
        public static string AccessLabel {
            get {
                return ResourceManager.GetString("AccessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjelder tilgang til å foreslå, endre- og slette egne registeroppføringer. Admin har alltid full tilgang.
        /// </summary>
        public static string AccessText {
            get {
                return ResourceManager.GetString("AccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godkjenningstekst.
        /// </summary>
        public static string ApprovalDocument {
            get {
                return ResourceManager.GetString("ApprovalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godkjenningsreferanse.
        /// </summary>
        public static string ApprovalReference {
            get {
                return ResourceManager.GetString("ApprovalReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lovlig innhold.
        /// </summary>
        public static string ContainedItemClass {
            get {
                return ResourceManager.GetString("ContainedItemClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det må settes lovlig innhold for registeret.
        /// </summary>
        public static string ContainedItemClassErrorMessage {
            get {
                return ResourceManager.GetString("ContainedItemClassErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innhold.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjeldende.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato godkjent.
        /// </summary>
        public static string DateAccepted {
            get {
                return ResourceManager.GetString("DateAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato utkast.
        /// </summary>
        public static string DateNotAccepted {
            get {
                return ResourceManager.GetString("DateNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato Tilbaketrukket.
        /// </summary>
        public static string DateRetired {
            get {
                return ResourceManager.GetString("DateRetired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato innsendt.
        /// </summary>
        public static string DateSubmitted {
            get {
                return ResourceManager.GetString("DateSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato erstattet.
        /// </summary>
        public static string DateSuperseded {
            get {
                return ResourceManager.GetString("DateSuperseded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definisjon.
        /// </summary>
        public static string Definition {
            get {
                return ResourceManager.GetString("Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er du sikker på at du vil slette.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivelse.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokument url.
        /// </summary>
        public static string DocumentUrl {
            get {
                return ResourceManager.GetString("DocumentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sti/url til HTML-versjon.
        /// </summary>
        public static string DocumentUrl2 {
            get {
                return ResourceManager.GetString("DocumentUrl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url til vedlegg.
        /// </summary>
        public static string DocumentUrlAttachment {
            get {
                return ResourceManager.GetString("DocumentUrlAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokument url engelsk.
        /// </summary>
        public static string DocumentUrlEnglish {
            get {
                return ResourceManager.GetString("DocumentUrlEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dekningskartet viser hvilke datasett i det offentlige kartgrunnlaget som har dekning i de ulike kommunene..
        /// </summary>
        public static string DOKCoverageContent {
            get {
                return ResourceManager.GetString("DOKCoverageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utkast.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rediger liste.
        /// </summary>
        public static string EditList {
            get {
                return ResourceManager.GetString("EditList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeret kan ikke slettes fordi det inneholder elementer som må slettes først!.
        /// </summary>
        public static string ErrorMessageDelete {
            get {
                return ResourceManager.GetString("ErrorMessageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feil verdi.
        /// </summary>
        public static string ErrorMessageValidationName {
            get {
                return ResourceManager.GetString("ErrorMessageValidationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etat.
        /// </summary>
        public static string Etat {
            get {
                return ResourceManager.GetString("Etat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodelister.
        /// </summary>
        public static string GroupCodeLists {
            get {
                return ResourceManager.GetString("GroupCodeLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datamodeller og standardisering.
        /// </summary>
        public static string GroupDatamodelsAndStandards {
            get {
                return ResourceManager.GetString("GroupDatamodelsAndStandards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentregister.
        /// </summary>
        public static string GroupDocumentRegistry {
            get {
                return ResourceManager.GetString("GroupDocumentRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status og rapportering.
        /// </summary>
        public static string GroupStatusAndReporting {
            get {
                return ResourceManager.GetString("GroupStatusAndReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolisering og kartografi.
        /// </summary>
        public static string GroupSymbolAndCartography {
            get {
                return ResourceManager.GetString("GroupSymbolAndCartography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historiske.
        /// </summary>
        public static string Historical {
            get {
                return ResourceManager.GetString("Historical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to treff.
        /// </summary>
        public static string Hits {
            get {
                return ResourceManager.GetString("Hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viser.
        /// </summary>
        public static string HitsDisplay {
            get {
                return ResourceManager.GetString("HitsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to av.
        /// </summary>
        public static string HitsOf {
            get {
                return ResourceManager.GetString("HitsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital kartografi.
        /// </summary>
        public static string Kartografi {
            get {
                return ResourceManager.GetString("Kartografi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeret inneholder datasett som har registrert digital kartografi.
        /// </summary>
        public static string KartografiContent {
            get {
                return ResourceManager.GetString("KartografiContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Henter register.
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sett status &quot;Utkast&quot; på alle kodeverdier.
        /// </summary>
        public static string MakeAllItemsDraft {
            get {
                return ResourceManager.GetString("MakeAllItemsDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sett status for alle verdier i kodelista. Individuelle verdier kan fortsatt settes.
        /// </summary>
        public static string MakeAllItemsDraftMessage {
            get {
                return ResourceManager.GetString("MakeAllItemsDraftMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sett status &quot;Tilbaketrukket&quot; på alle kodeverdier.
        /// </summary>
        public static string MakeAllItemsRetired {
            get {
                return ResourceManager.GetString("MakeAllItemsRetired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sett status for alle verdier i kodelista. Individuelle verdier kan fortsatt settes.
        /// </summary>
        public static string MakeAllItemsRetiredMessage {
            get {
                return ResourceManager.GetString("MakeAllItemsRetiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sett status &quot;Gyldig&quot; på alle kodeverdier.
        /// </summary>
        public static string MakeAllItemsValid {
            get {
                return ResourceManager.GetString("MakeAllItemsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sett status for alle verdier i kodelista. Individuelle verdier kan fortsatt settes.
        /// </summary>
        public static string MakeAllItemsValidMessage {
            get {
                return ResourceManager.GetString("MakeAllItemsValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siste endret.
        /// </summary>
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny versjon.
        /// </summary>
        public static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke angitt.
        /// </summary>
        public static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objektregisteret.
        /// </summary>
        public static string Objektregisteret {
            get {
                return ResourceManager.GetString("Objektregisteret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inneholder en samling av sentrale objektkataloger fra SOSI, Inspire og fra parter i Norge digitalt. Her finnes dataspesifikasjoner som er nyttige ved fremstilling av datasett, eller som dokumentasjon av hvordan innholdet og strukturen i et datasett skal tolkes..
        /// </summary>
        public static string ObjektregisteretContent {
            get {
                return ResourceManager.GetString("ObjektregisteretContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eier.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forslag.
        /// </summary>
        public static string Proposal {
            get {
                return ResourceManager.GetString("Proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreslå.
        /// </summary>
        public static string Propose {
            get {
                return ResourceManager.GetString("Propose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publiser.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;For å oppnå &lt;b&gt;god&lt;/b&gt; oppfyllelse av krav, må datasettet være tilgjengelig gjennom en atom feed-tjeneste som er registrert i Geonorge. Ellers blir status &lt;b&gt;ikke levert&lt;/&gt;.&lt;/p&gt;.
        /// </summary>
        public static string RequirementsAtom {
            get {
                return ResourceManager.GetString("RequirementsAtom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;For å oppnå &lt;b&gt;god&lt;/b&gt; oppfyllelse av krav, må datasettet være tilgjengelig gjennom en distribusjon av type Geonorge nedlasting. Ellers blir status &lt;b&gt;ikke levert&lt;/b&gt;.&lt;/p&gt;.
        /// </summary>
        public static string RequirementsDownload {
            get {
                return ResourceManager.GetString("RequirementsDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;For å oppnå &lt;b&gt;god&lt;/b&gt; oppfyllelse av krav, må nedlastbare GML-filer validere mot UML-modell i produktspesifikasjonen. Det vil gå fram av metadata om GML-filer er konforme med produktspesifikasjonen. Hvis det finnes nedlastbare GML-filer, så vil det kvalifisere til &lt;b&gt;brukbar&lt;/b&gt; oppfyllelse av krav. Ellers blir status &lt;b&gt;ikke levert&lt;/b&gt;.&lt;/p&gt;.
        /// </summary>
        public static string RequirementsGml {
            get {
                return ResourceManager.GetString("RequirementsGml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;For at metadatakvaliteten skal bli &lt;b&gt;god&lt;/b&gt;, må metadata validere i Geonorge sin metadataeditor. Det vil si at alle påkrevde felt skal være utfylt. Ellers blir metadata vurdert til &lt;b&gt;brukbar&lt;/b&gt; hvis de finnes. Ellers blir status &lt;b&gt;ikke angitt&lt;/b&gt;.&lt;/p&gt;.
        /// </summary>
        public static string RequirementsMetadata {
            get {
                return ResourceManager.GetString("RequirementsMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;For å oppnå &lt;b&gt;god&lt;/b&gt; oppfylleles av krav må dokumentasjonen være laget på ND-malen. Dokumentasjonen må være meningsfullt utfylt for alle felt.
        ///Må være tilgjengelig som SLD.
        ///&lt;b&gt;Brukbar:&lt;/b&gt; Dokumentasjonen er laget iht. annen mal enn ND-malen. Dokument eller SLD er tilgjengelig.&lt;/p&gt;.
        /// </summary>
        public static string RequirementsPresentationRulesStatus {
            get {
                return ResourceManager.GetString("RequirementsPresentationRulesStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;For å oppnå &lt;b&gt;god&lt;/b&gt; oppfylleles av krav må dokumentasjonen må være laget på ND-malen (Wordmal eller produktarkgenerator). Meningsfullt utfylt for alle felt.
        ///&lt;b&gt;Brukbar:&lt;/b&gt;  Dokumentasjonen er laget iht. annen mal enn ND-malen&lt;/p&gt;.
        /// </summary>
        public static string RequirementsProductSheetStatus {
            get {
                return ResourceManager.GetString("RequirementsProductSheetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;For å oppnå &lt;b&gt;god&lt;/b&gt; oppfyllelse av krav, må det refereres til godkjent SOSI produktspesifikasjon i metadata. Annen referert produktspesifikasjon vil kunne gi &lt;b&gt;brukbar&lt;/b&gt; oppfyllelse av krav. Ellers blir status &lt;b&gt;ikke angitt&lt;/b&gt;.&lt;/p&gt;.
        /// </summary>
        public static string RequirementsProductSpesifications {
            get {
                return ResourceManager.GetString("RequirementsProductSpesifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;For å oppnå &lt;b&gt;god&lt;/b&gt; oppfyllelse av krav, må nedlastbare SOSI-filer validere mot UML-modell i produktspesifikasjonen. Det vil gå fram av metadata om SOSI-filer er konforme med produktspesifikasjonen. Hvis det finnes nedlastbare SOSI-filer, så vil det kvalifisere til &lt;b&gt;brukbar&lt;/b&gt; oppfyllelse av krav. Ellers blir status &lt;b&gt;ikke levert&lt;/b&gt;.&lt;/p&gt;.
        /// </summary>
        public static string RequirementsSosi {
            get {
                return ResourceManager.GetString("RequirementsSosi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;For å oppnå &lt;b&gt;god&lt;/b&gt; oppfyllelse av krav, må det i metadata finnes en WFS-tjeneste. Ellers blir status &lt;b&gt;ikke levert&lt;/b&gt;.&lt;/p&gt;.
        /// </summary>
        public static string RequirementsWfs {
            get {
                return ResourceManager.GetString("RequirementsWfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;For å oppnå &lt;b&gt;god&lt;/b&gt; oppfyllelse av krav, må det i metadata finnes en WMS-tjeneste. Ellers blir status &lt;b&gt;ikke levert&lt;/b&gt;.&lt;/p&gt;.
        /// </summary>
        public static string RequirementsWms {
            get {
                return ResourceManager.GetString("RequirementsWms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilbaketrukket.
        /// </summary>
        public static string Retired {
            get {
                return ResourceManager.GetString("Retired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagrer innhold.
        /// </summary>
        public static string SavingContentMessage {
            get {
                return ResourceManager.GetString("SavingContentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mulige statuser.
        /// </summary>
        public static string StatusAvailable {
            get {
                return ResourceManager.GetString("StatusAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innsender.
        /// </summary>
        public static string Submitter {
            get {
                return ResourceManager.GetString("Submitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreslå nytt register.
        /// </summary>
        public static string SuggestNewRegister {
            get {
                return ResourceManager.GetString("SuggestNewRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreslå nytt register i.
        /// </summary>
        public static string SuggestNewRegisterIn {
            get {
                return ResourceManager.GetString("SuggestNewRegisterIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreslå ny versjon av.
        /// </summary>
        public static string SuggestNewVersionOf {
            get {
                return ResourceManager.GetString("SuggestNewVersionOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstattet.
        /// </summary>
        public static string Superseded {
            get {
                return ResourceManager.GetString("Superseded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dette registeret inneholder symboler som brukes til styling av digital kartografi, og til bruk i grafisk bransje..
        /// </summary>
        public static string SymbolContent {
            get {
                return ResourceManager.GetString("SymbolContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string SymbolName {
            get {
                return ResourceManager.GetString("SymbolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transliter æøå til eoa i url sti.
        /// </summary>
        public static string TransliterNorwegian {
            get {
                return ResourceManager.GetString("TransliterNorwegian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppdatert.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyldig.
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versjon.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versjon.
        /// </summary>
        public static string VersionName {
            get {
                return ResourceManager.GetString("VersionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versjons ID.
        /// </summary>
        public static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
    }
}
