//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceAlerts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceAlerts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kartverket.Register.Resources.ServiceAlerts", typeof(ServiceAlerts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varslingsdato.
        /// </summary>
        public static string AlertDate {
            get {
                return ResourceManager.GetString("AlertDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varslingsdato er påkrevd.
        /// </summary>
        public static string AlertDateErrorMessage {
            get {
                return ResourceManager.GetString("AlertDateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type varsel.
        /// </summary>
        public static string AlertType {
            get {
                return ResourceManager.GetString("AlertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valg av type varsel er påkrevd.
        /// </summary>
        public static string AlertTypeErrorMessage {
            get {
                return ResourceManager.GetString("AlertTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikrafttredelsesdato.
        /// </summary>
        public static string EffectiveDate {
            get {
                return ResourceManager.GetString("EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikrafttredelsesdato er påkrevd.
        /// </summary>
        public static string EffectiveDateErrorMessage {
            get {
                return ResourceManager.GetString("EffectiveDateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siste varsel.
        /// </summary>
        public static string LastAlert {
            get {
                return ResourceManager.GetString("LastAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varselet gjelder.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det er påkrevd å skrive hva varselet gjelder.
        /// </summary>
        public static string NoteErrorMessage {
            get {
                return ResourceManager.GetString("NoteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjeneste.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjenestebeskrivelse.
        /// </summary>
        public static string ServiceDesription {
            get {
                return ResourceManager.GetString("ServiceDesription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjenestenavn.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjenestetype.
        /// </summary>
        public static string ServiceType {
            get {
                return ResourceManager.GetString("ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valg av tjeneste er påkrevd.
        /// </summary>
        public static string ServiceTypeErrorMessage {
            get {
                return ResourceManager.GetString("ServiceTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abonnere på tjenestevarsler.
        /// </summary>
        public static string SubscribeServiceAlert {
            get {
                return ResourceManager.GetString("SubscribeServiceAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreslå nytt tjenestevarsel.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
