//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kartverket.Register.Resources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geonorge Register.
        /// </summary>
        public static string AppPageTitle {
            get {
                return ResourceManager.GetString("AppPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreslå ny organisasjon.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slett.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekreftelse på data som skal være kommunes DOK.
        /// </summary>
        public static string DOK_Bekreftet_Kommune {
            get {
                return ResourceManager.GetString("DOK_Bekreftet_Kommune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjonen som har et eierforhold til datene og kan svare inngående om faglige forhold rundt datasettets struktur og innhold.
        /// </summary>
        public static string DOK_Eier {
            get {
                return ResourceManager.GetString("DOK_Eier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Må legges inn på data en velger ikke å ta med, kan brukes også for andre datasett.
        /// </summary>
        public static string DOK_Kommentar {
            get {
                return ResourceManager.GetString("DOK_Kommentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasettet sin status.
        /// </summary>
        public static string DOK_Nasjonal_Status {
            get {
                return ResourceManager.GetString("DOK_Nasjonal_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viser om datasettet er nasjonalt eller kommunalt.
        /// </summary>
        public static string DOK_Nasjonalt_Kommunalt {
            get {
                return ResourceManager.GetString("DOK_Nasjonalt_Kommunalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasett overordnet kategorisering.
        /// </summary>
        public static string DOK_Temagruppe {
            get {
                return ResourceManager.GetString("DOK_Temagruppe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offisiell tittel (navn) på datasett.
        /// </summary>
        public static string DOK_Tittel {
            get {
                return ResourceManager.GetString("DOK_Tittel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rediger.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjon.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liten logo.
        /// </summary>
        public static string Organization_Logo {
            get {
                return ResourceManager.GetString("Organization_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjonsnavn.
        /// </summary>
        public static string Organization_Name {
            get {
                return ResourceManager.GetString("Organization_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjonsnummer.
        /// </summary>
        public static string Organization_Number {
            get {
                return ResourceManager.GetString("Organization_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjoner.
        /// </summary>
        public static string Organizations {
            get {
                return ResourceManager.GetString("Organizations", resourceCulture);
            }
        }
    }
}
